custom_modules_path: thor_terratorch_ext/thor_terratorch_ext
data:
  class_path: terratorch.datamodules.GenericMultiModalDataModule
  init_args:
    allow_substring_file_names: true
    batch_size: 8
    check_stackability: false
    concat_bands: true
    dataset_bands:
      S1:
      - VV
      - VH
      S2L2A:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - WATER_VAPOR
      - CIRRUS
      - SWIR_1
      - SWIR_2
    image_grep:
      S1: '*_S1Hand.tif'
      S2L2A: '*_S2Hand.tif'
    label_grep: '*_LabelHand.tif'
    means:
      S1:
      - -10.184386565394322
      - -16.89525461597349
      S2L2A:
      - 1396.0347063125125
      - 1364.0611841716463
      - 1218.228479188586
      - 1466.0729066303797
      - 2386.9029753700133
      - 2845.6125627699353
      - 2622.9579689237808
      - 3077.482214806572
      - 2030.6476302373976
      - 1179.16607220967
    modalities:
    - S2L2A
    - S1
    no_data_replace: 0
    no_label_replace: -1
    num_classes: 2
    num_workers: 15
    output_bands:
      S1:
      - VV
      - VH
      S2L2A:
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
    - 3
    - 2
    - 1
    rgb_modality: S2L2A
    stds:
      S1:
      - 4.255338143340657
      - 5.290564988051755
      S2L2A:
      - 739.0945268205048
      - 735.2482387959477
      - 864.9366949997807
      - 776.8803358037292
      - 921.3683430927466
      - 1084.3734609719752
      - 1022.6341800670566
      - 1196.4425531763263
      - 980.8706134697641
      - 764.6083655721079
    task: segmentation
    test_data_root:
      S1: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S1Hand
      S2L2A: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S2Hand
    test_label_data_root: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/LabelHand
    test_split: dataset/sen1floods11/sen1floods11/v1.1/splits/flood_handlabeled/flood_test_data.txt
    train_data_root:
      S1: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S1Hand
      S2L2A: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S2Hand
    train_label_data_root: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/LabelHand
    train_split: dataset/sen1floods11/sen1floods11/v1.1/splits/flood_handlabeled/flood_train_data.txt
    train_transform:
    - class_path: albumentations.RandomCrop
      init_args:
        height: 288
        width: 288
    - class_path: albumentations.D4
    - class_path: albumentations.pytorch.transforms.ToTensorV2
    val_data_root:
      S1: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S1Hand
      S2L2A: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/S2Hand
    val_label_data_root: dataset/sen1floods11/sen1floods11/v1.1/data/flood_events/HandLabeled/LabelHand
    val_split: dataset/sen1floods11/sen1floods11/v1.1/splits/flood_handlabeled/flood_valid_data.txt
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    factor: 0.5
    min_lr: 1e-6
    monitor: val/loss
    patience: 10
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    class_names:
    - Others
    - Flood
    freeze_backbone: false
    freeze_decoder: false
    ignore_index: -1
    loss: dice
    model_args:
      backbone: thor_v1_base
      backbone_input_params:
        flexivit_patch_size_seqs:
        - 8
        ground_covers:
        - 2880
      backbone_modalities:
      - S2L2A
      - S1
      backbone_model_bands:
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
      - VV
      - VH
      backbone_out_indices:
      - -1
      backbone_pretrained: true
      decoder: LinearDecoder
      decoder_num_classes: 2
      decoder_upsampling_size: 8
      head_dropout: 0.2
      necks:
      - name: THORGroupReshapeTokensToImage
      num_classes: 2
    model_factory: EncoderDecoderFactory
    plot_on_val: true
    tiled_inference_on_testing: true
    tiled_inference_on_validation: true
    tiled_inference_parameters:
      average_patches: true
      batch_size: 4
      h_crop: 288
      h_stride: 256
      w_crop: 288
      w_stride: 256
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 2e-5
    weight_decay: 0.05
seed_everything: 0
trainer:
  accelerator: auto
  callbacks:
  - class_path: RichProgressBar
  - class_path: LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: ModelCheckpoint
    init_args:
      monitor: val/loss
      save_last: true
      save_top_k: 1
  - class_path: EarlyStopping
    init_args:
      monitor: val/loss
      patience: 30
      verbose: true
  - class_path: src.callbacks.auto_test.AutoTestCallback
  check_val_every_n_epoch: 1
  default_root_dir: outputs/sen1floods11
  devices: auto
  enable_checkpointing: true
  log_every_n_steps: 1
  logger:
    class_path: WandbLogger
    init_args:
      group: Sen1Floods11
      name: sen1floods11/Thor_Sen1Floods11_UperNetDecoder
      save_dir: outputs
  max_epochs: 200
  num_nodes: 1
  precision: 16-mixed
  strategy: auto
