seed_everything: 0
custom_modules_path: ./thor_terratorch_ext
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 100
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  default_root_dir: ./results
  logger:
  - class_path: WandbLogger
    init_args:
      save_dir: ./results
      log_model: true
      name: mire_S2_multiclass_thor_tiny_frozen_upernet_ps32
  callbacks:
  - class_path: RichProgressBar
  - class_path: LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: EarlyStopping
    init_args:
      monitor: val/loss
      patience: 30
      mode: min
      check_finite: false
      verbose: true
  - class_path: ModelCheckpoint
    init_args:
      monitor: val/loss
      mode: min
      save_top_k: 1
      save_last: true
data:
  class_path: thor_terratorch_ext.datamodules.mire_map_module.MireMapNonGeoDataModule
  init_args:
    batch_size: 8
    num_workers: 2
    bands:
    - BLUE
    - GREEN
    - RED
    - RED_EDGE_1
    - RED_EDGE_2
    - RED_EDGE_3
    - NIR_BROAD
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    data_root: /shared/home/fschindlegger/thor_terratorch_ext/data/mires/raw/ftp.nr.no/outgoing/jooutgoing/fm4cs/data/mire_sdklsdklsd/crops_1024_v2
    mode: multiclass
    no_label_replace: 255
    no_data_replace: median
    means:
    - 0.1507
    - 0.1568
    - 0.1464
    - 0.2466
    - 0.1815
    - 0.2292
    - 0.2385
    - 0.2467
    - 0.1326
    - 0.0857
    stds:
    - 0.2529
    - 0.2545
    - 0.2592
    - 0.2205
    - 0.2493
    - 0.2304
    - 0.2184
    - 0.2082
    - 0.1178
    - 0.0917
    train_transform:
    - class_path: albumentations.CropNonEmptyMaskIfExistsCompat
      init_args:
        height: 288
        width: 288
        p: 1.0
        ignore_values:
        - 255
    - class_path: ToTensorV2
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      num_classes: 6
      backbone: terratorch_thor_vit_tiny_encoder_alibi_patch_size_embed_v1
      backbone_ckpt: /shared/home/fschindlegger/thor_terratorch_ext/pretrained/thor/thor_v1_vit_tiny.pt
      backbone_model_ckpt_type: encoder
      backbone_return_channel_params: true
      backbone_pretrained: true
      decoder: UperNetDecoder
      decoder_channels: 256
      head_dropout: 0.1
      head_channel_list:
      - 256
      necks:
      - name: THORGroupReshapeTokensToImage
      - name: LearnedInterpolateToPyramidal
      backbone_out_indices:
      - 2
      - 5
      - 8
      - 11
      backbone_input_params:
        ground_covers:
        - 2880
        flexivit_patch_size_seqs:
        - 32
      backbone_model_bands:
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    plot_on_val: 1
    model_factory: EncoderDecoderFactory
    tiled_inference_on_testing: true
    tiled_inference_on_validation: true
    tiled_inference_parameters:
      h_crop: 288
      h_stride: 256
      w_crop: 288
      w_stride: 256
      average_patches: true
      batch_size: 4
    loss:
    - dice
    - ce
    ignore_index: 255
    class_weights:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.5
    - 0.1
    freeze_backbone: true
    freeze_decoder: false
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    mode: min
    factor: 0.5
    patience: 20
    threshold: 0.001
