custom_modules_path: thor_terratorch_ext/thor_terratorch_ext
data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 2
    dataset_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    img_grep: '*_merged.tif'
    label_grep: '*.mask.tif'
    means:
    - 0.033349706741586264
    - 0.05701185520536176
    - 0.05889748132001316
    - 0.2323245113436119
    - 0.1972854853760658
    - 0.11944914225186566
    no_data_replace: 0
    no_label_replace: -1
    num_classes: 2
    num_workers: 15
    output_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    rgb_indices:
    - 2
    - 1
    - 0
    stds:
    - 0.02269135568823774
    - 0.026807560223070237
    - 0.04004109844362779
    - 0.07791732423672691
    - 0.08708738838140137
    - 0.07241979477437814
    test_data_root: dataset/burnscars/hls_burn_scars/data
    test_split: dataset/burnscars/hls_burn_scars/splits/test.txt
    train_data_root: dataset/burnscars/hls_burn_scars/data
    train_split: dataset/burnscars/hls_burn_scars/splits/train.txt
    train_transform:
    - class_path: albumentations.RandomCrop
      init_args:
        height: 288
        width: 288
    - class_path: albumentations.D4
    - class_path: albumentations.pytorch.ToTensorV2
    val_data_root: dataset/burnscars/hls_burn_scars/data
    val_split: dataset/burnscars/hls_burn_scars/splits/val.txt
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    factor: 0.5
    min_lr: 1e-6
    monitor: val/loss
    patience: 10
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    class_names:
    - Others
    - Burned
    freeze_backbone: false
    freeze_decoder: false
    ignore_index: -1
    loss: dice
    lr: 2.0e-05
    model_args:
      backbone: thor_v1_tiny
      backbone_input_params:
        flexivit_patch_size_seqs:
        - 4
        ground_covers:
        - 2880
      backbone_modalities:
      - S2L2A
      backbone_model_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
      backbone_out_indices:
      - -1
      backbone_pretrained: true
      decoder: LinearDecoder
      decoder_num_classes: 2
      decoder_upsampling_size: 4
      head_dropout: 0.2
      necks:
      - name: THORGroupReshapeTokensToImage
      num_classes: 2
    model_factory: EncoderDecoderFactory
    plot_on_val: true
    tiled_inference_on_testing: true
    tiled_inference_on_validation: true
    tiled_inference_parameters:
      average_patches: true
      batch_size: 4
      h_crop: 288
      h_stride: 256
      w_crop: 288
      w_stride: 256
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 2.0e-05
    weight_decay: 0.05
seed_everything: 0
trainer:
  accelerator: auto
  accumulate_grad_batches: 4
  callbacks:
  - class_path: RichProgressBar
  - class_path: LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: ModelCheckpoint
    init_args:
      monitor: val/loss
      save_last: true
      save_top_k: 1
  - class_path: EarlyStopping
    init_args:
      min_delta: 0.0
      monitor: val/loss
      patience: 30
      verbose: true
  - class_path: src.callbacks.auto_test.AutoTestCallback
  check_val_every_n_epoch: 1
  default_root_dir: outputs/burnscars
  devices: auto
  enable_checkpointing: true
  log_every_n_steps: 1
  logger:
    class_path: WandbLogger
    init_args:
      group: HLS_BurnScars
      name: burnscars/ThorBase_PS8_BurnScars
      save_dir: outputs
  max_epochs: 200
  num_nodes: 1
  precision: 16-mixed
  strategy: auto
